- name: mysql server installation
  apt: pkg=mysql-server state=latest
  register: mysqlinstall

- name: change mysql root password
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  when: mysqlinstall|changed
