---
- hosts: elkarbackup
  
  vars:
    - root_password: 'elkarbackup'
    - mysql_root_password: 'elkarbackup'

  tasks:

    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600
      sudo: yes

    - name: upgrade the distro
      apt: upgrade=yes
      sudo: yes

    - name: install packages
      apt: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - debconf
        - php5
        - php5-cli
        - rsnapshot
        - mysql-server
        - php5-mysql
        - acl
        - bzip2
        - python-mysqldb
        - python-pycurl
        - debconf-utils

    - name: change mysql root password
      mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost
      sudo: yes

    - name: add elkarbackup repo key
      apt_key: url=http://elkarbackup.org/apt/archive.gpg.key state=present
      sudo: yes
      tags:
        - elkarbackup

    - name: add elkarbackup repository
      apt_repository: repo='deb http://elkarbackup.org/apt/debian wheezy main' state=present
      sudo: yes
      tags:
        - elkarbackup

    - name: preconfigure elkarbackup 1/2 - dbadminname
      debconf: name=elkarbackup question='elkarbackup/dbadminname' value='root' vtype=string
      sudo: yes
      tags:
        - elkarbackup

    - name: preconfigure elkarbackup 2/2 - dbadminpassword
      debconf: name=elkarbackup question='elkarbackup/dbadminpassword' value={{ mysql_root_password }} vtype=password
      sudo: yes
      tags:
        - elkarbackup

    - name: elkarbackup installation
      apt: pkg=elkarbackup state=present
      sudo: yes
      tags:
        - elkarbackup

    - name: change root password
      user: name=root password={{ root_password }}
      sudo: yes
