- hosts: all
  sudo: True
  vars:
    - root_password: '$6$rounds=100000$jnFsIZUdGtCNMuxe$ZlWJFAKkrPB8UoBRFEtyTXEoRnVPByiIkispYF.VRCS67CRinaTvPixeRcduuKzHd15UMpy4qQ6uDls24Dro4/'
    - mysql_root_password: 'elkarbackup'
  
  roles:
    - { role: common, root_password: "{{ root_password }}" }
    - { role: mysql, mysql_root_password: "{{ mysql_root_password}}" }
    - { role: elkarbackup, version: stable}
